# Generated by Django 4.1.9 on 2024-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_ingredients_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video_guide_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Link to video guide'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
