# Generated by Django 4.1.9 on 2024-11-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_video_guide_url_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='video_guide_url',
            new_name='video_guide',
        ),
    ]
