# Generated by Django 4.1.9 on 2024-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_video_guide_url_recipe_video_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_guide',
            field=models.URLField(),
        ),
    ]
