# Generated by Django 4.1.9 on 2024-11-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_video_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_guide',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Link to video guide'),
        ),
    ]
